Repository monsieurbiz/SyliusHomepagePlugin, pull requests merged in 2021-04, with the labels that each got.

#15 Make test green
  .github/workflows/recipe.yaml
  .github/workflows/security.yaml
  .github/workflows/tests.yaml
Labels: Status: needs review

#17 Change crud in admin routes
  src/Resources/config/routes/admin.yaml
Labels: Status: needs review

#18 Locale column length set to 10
  src/Entity/.gitignore
  src/Entity/HomepageTranslation.php
  src/Migrations/Version20210311135118.php
Labels: Status: needs review, quick win

#19 Inject Migrations using the DI
  src/DependencyInjection/MonsieurBizSyliusHomepageExtension.php
  src/Resources/config/app/doctrine_migrations.yaml
  src/Resources/config/config.yaml
Labels: Status: needs review, enhancement, quick win
